<?php
define('protect','1');
include('./app/includes/config.php');
include('./app/includes/core.php');
include('./app/theme/header.php');
?>
<?php
include('./app/includes/posts.php');
include('./app/theme/footer.php');
die();
?>